# version: "3.8"

services:
  mongo-db:
    image: mongo:6.0
    container_name: db_vaccination
    restart: always

    ports:
      - "${DB_PORT}:${DB_PORT}"

    volumes:
      - ./mongo-data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
